default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  adapter: postgresql
  encoding: unicode
  database: makersairbnb
  pool: 2
  

production:
  adapter: postgresql
  encoding: unicode
  database: makersairbnbprod
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: makersairbnbtest
  pool: 2
 