default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  
production:
  <<: *default
  database: makersairbnbprod

development:
  <<: *default
  database: makersairbnb

test:
  <<: *default
  database: makersairbnbtest